# Generated by Django 5.2.10 on 2026-03-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gallerycategory_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
