"""
Django settings for restaurant project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9z@27av24e2tg8uakyf(_%ho6nigs84e4@c(xw1*iz_otbj-!y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'cloudinary_storage', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'accounts',
    'menu',
    'cart',
    'orders',
    'payments',
    'tablebooking',
    'blog',
    'core',
    'chat',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
]

# Cloudinary এর সেটিংস (আপনার Cloudinary ড্যাশবোর্ড থেকে এই মানগুলো নিন)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'royaldine',
    'API_KEY': '791983312715839',
    'API_SECRET': 'U75ac8ookDKG4y4Zl5NhaQqBi4A'
}
# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '47e7c8396d26b7' # এখানে ইউজার আইডি দিন
EMAIL_HOST_PASSWORD = 'b67c9e1b429f48' # এখানে পাসওয়ার্ড দিন
EMAIL_PORT = '2525'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# ডিফল্ট ইমেইল এড্রেস যা কাস্টমার দেখবে
# settings.py এর ভেতরে এটি পরিবর্তন করুন
DEFAULT_FROM_EMAIL = 'noreply@royaldine.com'
# মিডিয়া ফাইল হিসেবে ক্লাউডিনারিকে সেট করুন
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ২. সাইট আইডি (জ্যাঙ্গো সাইট ফ্রেমওয়ার্কের জন্য)
SITE_ID = 1

# ৩. অথেনটিকেশন ব্যাকএন্ড (পাইথন যেন সোশ্যাল লগইন চিনতে পারে)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ৪. মিনিমাল কনফিগারেশন (যাতে ইউজারকে বারবার ফর্ম ফিলাপ করতে না হয়)
SOCIALACCOUNT_AUTO_SIGNUP = True # সরাসরি লগইন হবে, কোনো অতিরিক্ত ফর্ম ছাড়াই
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False # ইউজারনেম লাগবে না
ACCOUNT_AUTHENTICATION_METHOD = 'email' # ইমেইল দিয়ে লগইন হবে
LOGIN_REDIRECT_URL = '/' # লগইন শেষে হোম পেজে যাবে

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # এই লাইনটি যোগ করুন (সবচেয়ে গুরুত্বপূর্ণ)
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'restaurant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STRIPE_PUBLIC_KEY = os.environ.get("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# মিডিয়া ফাইল সেটিংস (Cloudinary এর জন্য এটি জরুরি)
MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# static files এর নিচে এই লাইনটিও চেক করে নিন
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' # এটি যোগ করে রাখা ভালো

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py এর শেষে
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

# এটি দিলে সরাসরি গুগল লগইন শুরু হবে, কনফার্মেশন পেজ আসবে না
SOCIALACCOUNT_LOGIN_ON_GET = True
   