# Generated by Django 5.2.10 on 2026-02-17 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('guest_count', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Lunch', 'Lunch (12:00 PM - 04:00 PM)'), ('Dinner', 'Dinner (07:00 PM - 11:00 PM)')], max_length=10)),
                ('booking_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Lunch', 'Lunch (12:00 PM - 04:00 PM)'), ('Dinner', 'Dinner (07:00 PM - 11:00 PM)')], max_length=10)),
                ('total_tables', models.PositiveIntegerField(default=10)),
                ('booked_tables', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'shift')},
            },
        ),
    ]
