# Generated by Django 5.2.10 on 2026-02-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0003_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
