# Generated by Django 5.2.10 on 2026-03-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How can we help?', max_length=100)),
                ('messenger_id', models.CharField(help_text='আপনার ফেসবুক পেজের ইউজারনেম বা আইডি', max_length=100)),
                ('phone_number', models.CharField(help_text='পাবলিক কন্টাক্ট নাম্বার', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('theme_color', models.CharField(default='#0084FF', max_length=7)),
                ('auto_hide_call_at_night', models.BooleanField(default=True)),
                ('night_start_hour', models.IntegerField(default=22)),
                ('night_end_hour', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name_plural': 'Widget Settings',
            },
        ),
    ]
