# Generated by Django 5.2.10 on 2026-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_today_special',
            field=models.BooleanField(default=False),
        ),
    ]
