# Generated by Django 5.2.10 on 2026-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_food_ai_tags_food_calories_food_carbs_food_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_surprise_item',
            field=models.BooleanField(default=False),
        ),
    ]
