# Generated by Django 5.2.10 on 2026-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_food_mood_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='food',
            name='off_peak_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
