# Generated by Django 5.2.10 on 2026-03-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, verbose_name='সাপ্তাহিক বন্ধ?')),
            ],
            options={
                'verbose_name': 'Operating Hour',
                'verbose_name_plural': 'Operating Hours',
                'ordering': ['day'],
            },
        ),
    ]
